name: Build and Deploy (Vue SPA)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}

defaults:
    run:
      working-directory: ./client

jobs:
  imported:
    uses: peruibeloko/shared/.github/workflows/vue.yml@main